services:
  padrao-nginx:
    image: nginx:alpine
    hostname: padrao-nginx
    container_name: padrao-nginx
    restart: always
    volumes:
      - ./src:/var/www/html/padrao
      - ./config/conf.d:/etc/nginx/conf.d
    depends_on:
      - padrao-php
    networks:
      - proxy
  padrao-php:
    image: homelab/php:8.2
    hostname: padrao-php
    container_name: padrao-php
    restart: always
    build:
      context: ../../infra/php/82
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./src:/var/www/html/padrao
      - ~/.ssh:/home/proxy/.ssh:ro
    working_dir: /var/www/html/padrao
    networks:
      - proxy
      - internal 
networks:
  proxy:
    external: true
  internal:
    external: true