services:
  homelabweb:
    image: nginx:latest
    hostname: homelabweb
    container_name: homelabweb
    working_dir: /var/www
    ports:
      - 82:80
    volumes:
      - ./www:/var/www
      - ./config/nginx/sites-available:/etc/nginx/sites-available
      - ./config/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      lan:
  homelabrds:
    image: mysql:latest
    hostname: homelabrds
    container_name: homelabrds
    ports:
     - 3308:3306  
    volumes:
      - ./docker/volumes/mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=homelab
      - MYSQL_USER=homelab
      - MYSQL_PASSWORD=homelab123
    restart: unless-stopped
    networks:
      lan:
networks:
  lan:
    driver: bridge
