server {
    listen 80;
    server_name projeto2.localhost;
    index index.php index.html index.htm;
    root /var/www/newton/projeto2;

    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        proxy_pass http://php2.local;
    }
}