services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - ${RDS_PORT}:3306    
    restart: unless-stopped
    command:
      - --require_secure_transport=OFF 
    environment:
      - MYSQL_ROOT_PASSWORD=${RDS_ROOT_PASSWORD}
      - MYSQL_DATABASE=${RDS_DATABASE}
      - MYSQL_USER=${RDS_USER}
      - MYSQL_PASSWORD=${RDS_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      - ./backups:/var/www/backups
    networks:
      - internal

# other common services

networks:
  internal:
    name: internal
    driver: bridge