#!/bin/bash
# Arquivo: comandos/ft-infra

SUBCOMANDO="$1"
shift

# Função para tratar override do Compose
drc() {
    if [[ -f "$(pwd)/docker-compose.override.yml" ]]; then
        docker compose -f docker-compose.override.yml "$@"
    else
        docker compose "$@"
    fi
}

help() {
    echo "Uso: ft infra [comando]"
    echo ""
    echo "Comandos:"
    echo "artisan  Executa o artisan"
    echo "composer Executa o composer"
    echo "php      Executa o php"
    exit 1
}

case "$SUBCOMANDO" in
    artisan)
        drc exec $(basename "$(pwd)")-php php artisan "$@"
        ;;
    composer)
        drc exec $(basename "$(pwd)")-php composer "$@"
        ;;
    mysql)
        docker exec -it rds mysql "$@"
        ;;
    nrd)
        if [[ -f "$(pwd)/src/package.json" ]]; then
            npm run dev --prefix ./src
        else
            npm run dev
        fi
        ;;
    php)
        drc exec $(basename "$(pwd)")-php php "$@"
        ;;
    tinker)
        drc exec  $(basename "$(pwd)")-php php artisan tinker "$@"
        ;;
    *)
        help
        ;;
esac
