services:

  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui

    restart: unless-stopped

    depends_on:
      ollama:
        condition: service_healthy

    environment:
      OLLAMA_BASE_URL: http://localhost:11435
      WEBUI_URL: http://ollama.web.home

    volumes:
      - ./data/webui:/app/backend/data

    networks:
      - proxy

    mem_limit: 768m
    cpus: 1

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true