server {
    listen 80;
    server_name financeiro.home;
    #index index.php index.html index.htm;

    location / {
        proxy_pass http://financeiro_nginx:80;
        proxy_set_header Host $host;
    }

}